# Generated by Django 4.1.5 on 2023-01-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('differenttest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
